# Generated by Django 3.2.12 on 2024-09-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudData',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('customer_id', models.IntegerField()),
                ('merchant_id', models.IntegerField()),
                ('transaction_data', models.DateTimeField()),
            ],
        ),
    ]
