# Generated by Django 3.2.12 on 2024-09-13 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FraudData',
        ),
    ]
