# Generated by Django 3.2.12 on 2024-09-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fraud', '0002_delete_frauddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudData',
            fields=[
                ('transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('customer_id', models.IntegerField()),
                ('merchant_id', models.IntegerField()),
                ('transaction_date', models.DateTimeField()),
            ],
        ),
    ]
