# Generated by Django 3.2.12 on 2024-09-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0005_remove_frauddata_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_id', models.CharField(max_length=100)),
                ('merchant_id', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
